---
name: Math-Random-OO
version: 0.21
author:
  - 'David A Golden <dagolden@cpan.org>'
abstract: |-
  Consistent object-oriented interface for generating random
  numbers
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0.18
  Params::Validate: 0.76
  Test::MockRandom: 0.95
  Test::More: 0.47
  Test::Number::Delta: 0.14
  perl: 5.006
provides:
  Math::Random::OO:
    file: lib/Math/Random/OO.pm
    version: 0.21
  Math::Random::OO::Bootstrap:
    file: lib/Math/Random/OO/Bootstrap.pm
    version: 0.21
  Math::Random::OO::Normal:
    file: lib/Math/Random/OO/Normal.pm
    version: 0.21
  Math::Random::OO::Uniform:
    file: lib/Math/Random/OO/Uniform.pm
    version: 0.21
  Math::Random::OO::UniformInt:
    file: lib/Math/Random/OO/UniformInt.pm
    version: 0.21
generated_by: Module::Build version 0.3201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
